# Runs test related tasks.

name: test

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  test:

    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install Java
      run: |
        sudo apt install openjdk-11-jdk
    - name: Install Nextflow
      run: |
        # Install latest version of Nextflow
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/bin
    - name: Install Docker
      run: |
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - uses: actions/checkout@v2
    - name: Pytest
      run: |
        pytest tests
    - name: Regression tests
      run: |
        ./tests/regression_tests.sh -s
      shell: bash
