# Runs test related tasks.

name: test

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  test:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests
    - name: Install Nextflow
      run: |
        # Install latest version of Nextflow
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/bin
    - name: Regression tests
      run: ./tests/regression_tests.sh -s
      shell: bash
